{% set version = "1.1.3" %}

package:
  name: docsteady
  version: {{ version }}

source:
  git_url: https://github.com/lsst-dm/docsteady.git
  git_rev: {{ version }}

build:
  noarch: python
  number: 1
  script: $PYTHON setup.py install
  entry_points:
    - docsteady = docsteady:cli

requirements:
  host:
    - python
    - pip
    - click
    - arrow
    - marshmallow 2.18
    - setuptools_scm
    - sphinx
    - sphinx-click
    - sphinx-rtd-theme
    - requests
    - jinja2
    - BeautifulSoup4
    - pyandoc
  run:
    - python
    - requests
    - jinja2
    - click
    - BeautifulSoup4
    - marshmallow 2.18
    - pyandoc
    - arrow

about:
  home: https://github.com/lsst-dm/docsteady
  license: GPL
